web:
  image: nginx:alpine
  volumes:
    - ./src:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build: .
  volumes:
    - ./src:/code
  env_file:
    - ./.env
mysql:
  image: mysql:latest
  env_file:
    - ./.env
  volumes:
    - /var/lib/docker/ext-volumes/mysql:/var/lib/mysql
